name: Docker Image CI

on: push


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx manually
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
          
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag ghcr.io/impossible-bosses/ibce-bot:latest \
          --push .
            
