name: verify

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: [self-hosted]
    timeout-minutes: 5

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python Requirements
        run: python3 -m pip install -r ./requirements.txt

      - name: pytest
        run: python3 -m pytest
